version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my-network

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

